// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.realdolmen.domain;

import com.realdolmen.domain.Pricing;

/************************************************************/
/**
 * 
 */
public abstract class abstractTravelingClassData {
	/**
	 * 
	 */
	private Pricing pricing;
	/**
	 * 
	 */
	private int remainingSeats;
};
