// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.realdolmen.domain;

/************************************************************/
/**
 * 
 */
public class BusinessClassData extends abstractTravelingClassData {
};
