// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.realdolmen.domain;

import com.realdolmen.domain.CreditCardType;

/************************************************************/
/**
 * 
 */
public class CreditCard {
	/**
	 * 
	 */
	private CreditCardType typeCreditCard;
};
