// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package com.realdolmen.domain;

/************************************************************/
/**
 * 
 */
public class Pricing {
	/**
	 * 
	 */
	private double defaultPrice;
	/**
	 * 
	 */
	private double basePrice;
	/**
	 * 
	 */
	private double discount;
};
